//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por SegundoAvancePA.rc
//
#define DLG_USUARIOSMODIFICAR           9
#define DLG_INICIOSESION                101
#define DLG_MENU                        103
#define DLG_USUARIOAGREGAR              113
#define DLG_USUARIOMOSTRAR              115
#define DLG_USUARIOELIMINAR             121
#define DLG_SUCURSALAGREGAR             123
#define DLG_SUCURSALESMOSTRAR           125
#define DLG_SUCURSALMODIFICAR           127
#define DLG_CLIENTESAGREGAR             129
#define IDD_DIALOG1                     131
#define DLG_CLIENTESMOSTRAR             131
#define DLG_CLIENTESMODIFICAR           133
#define IDD_DIALOG2                     137
#define IDD_DIALOG3                     139
#define DLG_PROMOAGREGAR                141
#define IDD_DIALOG4                     143
#define DLG_PROMOMOSTRAR                143
#define DLG_PROMOMODIFICAR              145
#define IDD_DIALOG5                     147
#define DLG_PROMOPUNTOS                 147
#define IDR_MENU1                       149
#define DLG_CLIENTESELIMINAR            150
#define DLG_SUCURSALESELIMINAR          152
#define IDD_DIALOG6                     154
#define DLG_PROMOELIMINAR               154
#define DLG_REGISTRAR                   156
#define IDD_DIALOG7                     158
#define DLG_REPORTEPUNTAJECLIENTES      158
#define IDD_DIALOG8                     160
#define DLG_CANJEARELEGIRCLIENTE        160
#define DLG_CANJEARPROMO                162
#define DLG_REPORTEPROMO                164
#define LBX_LISTREPORTEDINERO           166
#define DLG_REPORTEDINERO               166
#define TXT_USUARIO                     1001
#define TXT_PASSWORD                    1002
#define BTN_INICIOSESION                1003
#define BTN_SALIR                       1004
#define BTN_LIMPIAR                     1004
#define LBL_ERRORPASS                   1005
#define LBL_ERRORUS                     1006
#define BTN_USUARIOSAGREGAR             1007
#define BTN_CLIENTESAGREGAR             1008
#define BTN_SUCURSALESAGREGAR           1010
#define LBL_USUARIOMENU                 1011
#define LBL_NOMBREMENU                  1012
#define LBL_TIPOUSMENU                  1013
#define BTN_MOSTRARUSUARIOS             1034
#define BTN_USUARIOSMOSTRAR             1034
#define BTN_CLIENTESMODIFICAR           1035
#define BTN_USUARIOSMODIFICAR           1036
#define BTN_USUARIOSELIMINAR            1037
#define BTN_PROMOMODIFICAR              1038
#define BTN_PROMOMOSTRAR                1039
#define BTN_PROMOAGREGAR                1040
#define BTN_SUCURSALESMODIFICAR         1041
#define BTN_SUCURSALESMOSTRAR           1042
#define BTN_CLIENTESMOSTRAR             1045
#define TXT_USUARIONOMBRE               1047
#define TXT_USUARIOUSER                 1048
#define TXT_USUARIOPASSWORD             1049
#define IDC_EDIT4                       1050
#define TXT_USUARIOTIPO                 1050
#define TXT_MODTIPO                     1050
#define TXT_REGISTRARSUCURSAL           1050
#define BTN_USUARIOAGREGAR              1051
#define LBL_ERRORUSUARIOAGREGAR         1052
#define BTN_USUARIOAGREGARATRAS         1053
#define BTN_USUARIOAGREGARSALIR         1053
#define TXT_USUARIOSUCURSAL             1054
#define IDC_LIST1                       1055
#define LBX_USUARIOSSUCURSALES          1055
#define LBX_LISTUSUARIOS                1055
#define LBX_LISTUSUARIOSMOD             1055
#define LBX_LISTUSUARIOSELIMINAR        1055
#define LBX_LISTSUCURSALESMOS           1055
#define LBX_LISTSUCURSALMOD             1055
#define LBX_LISTCLIENTESMOSTRAR         1055
#define LBX_LISTCLIENTESMOD             1055
#define LBX_LISTPMOS                    1055
#define LBX_LISTPMOD                    1055
#define LBX_LISTPPUNTOSCLIENTES         1055
#define LBX_LISTCLIENTESELIMINAR        1055
#define LBX_LISTSUCURSALELIMINAR        1055
#define LBX_LISTPROMOELIMINAR           1055
#define TXT_REGISTRARLISTSUCURSALES     1055
#define LBX_REGISTRARLISTSUCURSALES     1055
#define LBX_REPORTEPUNTOSLIST           1055
#define LBX_LISTCLIENTESCANJEAR         1055
#define LBX_LISTCANJEPROMO              1055
#define LBX_LISTREPORTEPROMO            1055
#define IDC_EDIT1                       1057
#define TXT_MODNOMBRE                   1057
#define TXT_SUCURSALNOMBRE              1057
#define TXT_SUCURSALMODNOMBRE           1057
#define TXT_CLIENTESAGREGARNOMBRE       1057
#define TXT_CLIENTESMODNOMBRE           1057
#define TXT_PAGREGARNOMBRE              1057
#define LBL_PMODNOMBRE                  1057
#define TXT_PMODNOMBRE                  1057
#define TXT_PPUNTOSVENTA                1057
#define TXT_REGISTRARNOMBRE             1057
#define TXT_VENTACANJE                  1057
#define LBL_SUCURSALMENU                1058
#define LBL_MOSTRARNOMBRE               1059
#define LBL_MOSTRARUSER                 1060
#define LBL_MOSTRARPASSWORD             1061
#define LBL_MOSTRARTIPO                 1062
#define LBL_MOSTRARSUCURSAL             1063
#define BTN_MOSTRARUSERSALIR            1064
#define TXT_MODUSER                     1065
#define TXT_MODPASSWORD                 1066
#define TXT_MODSUCURSAL                 1067
#define BTN_MODIFICARUSUARIO            1068
#define BTN_SALIRMODUSER                1069
#define LBL_ERRORMENU                   1070
#define LBX_MODUSERSUCURSAL             1071
#define LBL_ERRORMODUSER                1072
#define BTN_SALIRELIMINARUSER           1074
#define LBL_USERNOMBELIMINAR            1075
#define LBL_USERUSUARIOELIMINAR         1076
#define LBL_USERPASSWORDELIMINAR        1077
#define LBL_USERTIPOELIMINAR            1078
#define LBL_USERSUCURSALELIMINAR        1079
#define LBL_ELIMINARAVISO               1080
#define TXT_SUCURSALDIRECCION           1081
#define LBL_SUCURSALAGREGARERROR        1082
#define BTN_AGREGARSUCURSAL             1083
#define BTN_SUCURSALAGREGARSALIR        1084
#define LBL_SUCURSALMOSTRARNOMBRE       1085
#define LBL_                            1086
#define LBL_SUCURSALMOSDIRECCION        1086
#define BTN_SALIRMOSSUCU                1087
#define IDC_EDIT2                       1088
#define TXT_SUCURSALMODDIRECCION        1088
#define TXT_CLIENTESAGREGAREMAIL        1088
#define TXT_CLIENTEMOD                  1088
#define TXT_CLIENTESMODCORREO           1088
#define BTN_PROMOAGREGARPUNTOS          1088
#define TXT_PAGREGARPUNTOS              1088
#define TXT_PMODPUNTOS                  1088
#define TXT_REGISTRARUSER               1088
#define BTN_SUCURSALMOD                 1089
#define LBL_ERRORMODSUC                 1090
#define BTN_SALIRSUCMOD                 1091
#define LBL_SUCURSALMODID               1092
#define LBL_USUARIOMODID                1093
#define LBL_CLIENTESAGREGARERROR        1094
#define LBL_CLIENTESAGREGARSUCURSAL     1095
#define LBL_CLIENTESAGREGARFECHA        1096
#define BTN_CLIENTESAGREGARSALIR        1097
#define BTN_CLIENTESMOSTRARSALIR        1098
#define LBL_CLIENTESMOSTRARNOMBRE       1099
#define LBL_CLIENTESMOSTRAREMAIL        1100
#define LBL_CLIENTESMOSTRARSUCURSAL     1101
#define LBL_CLIENTESMOSTRARFECHA        1102
#define LBL_CLIENTESMOSTRARPUNTOS       1103
#define BTN_CLIENTESMODIFICARSALIR      1104
#define LBL_CLIENTESMODSUCURSAL         1105
#define LBL_CLIENTESMODPUNTOS           1106
#define LBL_CLIENTESMODFECHA            1107
#define BTN_CLIENTEMODIFICAR            1108
#define LBL_CLIENTESMODERROR            1109
#define LBL_CLIENTESMODID               1110
#define IDC_EDIT3                       1113
#define BTN_PROMOAGREGARDESCUENTO       1113
#define TXT_PAGREGARDESCUENTO           1113
#define TXT_PMODDESCUENTO               1113
#define TXT_REGISTRARPASS               1113
#define IDC_BUTTON2                     1124
#define BTN_PAGREGARDESACTIVAR          1124
#define BTN_PMODDESACTIVAR              1124
#define IDC_BUTTON1                     1130
#define BTN_PAGREGARACTIVAR             1130
#define BTN_PMODACTIVAR                 1130
#define BTN_PROMOPUNTOS                 1130
#define BTN_USUARIOSMODCARGARIMG        1130
#define BTN_REPORTEPUNTOSCSV            1130
#define BTN_REPORTEPROMOEXPORT          1130
#define BTN_REPORTEDINEROEXPORT         1130
#define LBL_PAGREGARESTATUS             1131
#define BTN_PAGREGAR                    1132
#define LBL_PAGREGARERROR               1133
#define BTN_PAGREGARSALIR               1134
#define LBL_PMOSNOMBRE                  1135
#define LBL_PMOSPUNTOS                  1136
#define LBL_PMOSDESCUENTO               1137
#define LBL_PMOSESTATUS                 1138
#define BTN_PMOSSALIR                   1139
#define LBL_PMODESTATUS                 1141
#define LBL_PMODERROR                   1142
#define LBL_PMODID                      1143
#define BTN_PMODMODIFICAR               1144
#define BTN_PMODSALIR                   1145
#define BTN_PAGREGARPUNTOS              1146
#define BTN_PSALIR                      1147
#define LBL_PPUNTOSNOMBRE               1150
#define LBL_PPUNTOSCORREO               1151
#define LBL_PPUNTOSFECHA                1152
#define LBL_PPUNTOSSUCURSAL             1153
#define LBL_PPUNTOSCLIENTEPUNTOS        1154
#define LBL_PPUNTOSID                   1155
#define LBL_PPUNTOSERROR                1156
#define LBL_CLIENTESELIMINARNOMBRE      1158
#define LBL_CLIENTESELIMINARCORREO      1159
#define LBL_CLIENTESELIMINARSUCURSAL    1160
#define LBL_CLIENTESELIMINARFECHA       1161
#define BTN_CLIENTESELIMINAR            1162
#define BTN_CLIENTESELIMINARSALIR       1163
#define LBL_CLIENTESELIMINARAVISO       1164
#define LBL_CLIENTESELIMINARID          1165
#define LBL_CLIENTESELIMINARPUNTOS      1166
#define LBL_SUCURSALELIMINARAVISO       1167
#define LBL_SUCURSALELIMINARNOMBRE      1168
#define LBL_SUCURSALELIMINARDIRECCION   1169
#define LBL_SUCURSALELIMINARID          1170
#define LBL_PROMOELIMINARID             1172
#define LBL_PROMOELIMINARNOMBRE         1173
#define LBL_PROMOELIMINARPUNTOS         1174
#define LBL_PROMOELIMINARDESCUENTO      1175
#define LBL_PROMOELIMINARESTADO         1176
#define LBL_PROMOELIMINARAVISO          1177
#define _PROMOELIMINAR                  1178
#define BTN_PROMOELIMINAR               1178
#define BTN_PROMOELIMINARSALIR          1179
#define BTN_SUCURSALELIMINAR            1180
#define BTN_SUCURSALELIMINARSALIR       1181
#define PC_IMGMENU                      1182
#define BTN_USUARIOAGREGARCARGAR        1183
#define PC_USUARIOAGREGARIMAGEN         1184
#define RB_REGISTRARADMIN               1185
#define RB_REGISTRARCAJERO              1186
#define PC_REGISTRARIMG                 1187
#define BTN_REGISTRARCARGARIMG          1188
#define BTN_REGISTRAR                   1189
#define BTN_REGISTRARSALIR              1190
#define LBL_REGISTRARAVISO              1191
#define BTN_INICIOSESIONREGISTRAR       1192
#define RB_USUARIOAGREGARADMIN          1193
#define IDC_RADIO2                      1194
#define RB_USUARIOAGREGARCAJERO         1194
#define RB_USUARIOSMODCAJERO            1194
#define LBL_CLIENTESUS                  1195
#define LBL_CLIENTESELIMINARUSER        1196
#define LBL_CLIENTESMODUS               1197
#define LBL_CLIENTESMOSTRARUS           1198
#define PC_USUARIOSMODIMG               1199
#define LBL_USUARIOSMODUS               1200
#define IDC_RADIO1                      1201
#define RB_USUARIOSMODADMIN             1201
#define PC_USUARIOAGREGARIMGUS          1202
#define PC_USUARIOMOSTRARIMGUS          1203
#define PC_USUARIOMODIMG                1204
#define PC_USUARIOELIMINARIMG           1205
#define PC_USUARIOSMOSIMG               1206
#define PC_USUARIOSELIMINARIMG          1207
#define PC_SUCURSALIMGELIMINAR          1208
#define PC_SUCURSALESIMGAGREGAR         1209
#define PC_SUCURSALESMOSTRARIMG         1210
#define PC_SUCURSALMODIMG               1211
#define PC_CLIENTESAGREGARIMG           1212
#define PC_CLIENTESMOSIMG               1213
#define PC_CLIENTESMODIMG               1214
#define PC_CLIENTESELIMINARIMG          1215
#define PC_PROMOELIMINARIMG             1216
#define PC_PROMOAGREGARIMG              1217
#define PC_PROMOMOSIMG                  1218
#define PC_PROMOMODIMG                  1219
#define PC_PROMOPUNTOSIMG               1220
#define LBL_NOMBREUSSESION              1221
#define IDC_STATIC1                     1222
#define IDC_STATIC2                     1223
#define IDC_STATIC3                     1224
#define IDC_STATIC4                     1225
#define IDC_STATIC5                     1226
#define IDC_STATIC6                     1227
#define IDC_STATIC8                     1229
#define IDC_STATIC0                     1230
#define IDC_STATIC11                    1231
#define IDC_STATIC12                    1232
#define IDC_STATIC14                    1233
#define PC_REPORTEPUNTOSIMGUS           1234
#define LBL_REPORTEPUNTOSNOMBRE         1235
#define BTN_REPORTEPUNTOSSALIR          1236
#define BTN_SIG                         1237
#define BTN_CANJEARREGRESA              1238
#define LBL_CANJEARNOMBREUS             1239
#define PC_CANJEAR                      1240
#define LBL_PUNTOSCANJEAR               1241
#define LBL_CANJENOMBREPROMO            1242
#define LBL_CANJEPUNTOSPROMO            1243
#define LBL_CANJEDESCUENTOPROMO         1244
#define LBL_CANJEESTATUSPROMO           1245
#define LBL_CANJEDESCUENTOFINAL         1246
#define LBL_CANJEPUNTOSCLIENTE          1247
#define BTN_CANJEARPROMO                1248
#define BTN_REGRESARCANJEPROMO          1249
#define LBL_AVISOCANJEAR                1250
#define LBL_CANJEARNOMBRECLIENTE        1251
#define LBL_CANJEARCLIENTEAVISO         1252
#define LBL_CANJEARPROMOID              1253
#define PC_CANJEARPROMO                 1254
#define LBL_CANJEARPROMOUS              1255
#define BTN_REPORTEPROMOSALIR           1256
#define LBL_REPORTENOMBREUS             1257
#define PC_REPORTEPROMO                 1258
#define PC_REPORTEDINERO                1259
#define LBL_REPORTEDINEROUS             1260
#define BTN_REPORTEDINEROSALIR          1261
#define IDC_MONTHCALENDAR1              1262
#define ID_USUARIOS_AGREGAR             40001
#define ID_USUARIOS_MOSTRAR             40002
#define ID_USUARIOS_MODIFICAR           40003
#define ID_USUARIOS_ELIMINAR            40004
#define ID_CLIENTES_AGREGAR             40005
#define ID_CLIENTES_MOSTRAR             40006
#define ID_CLIENTES_MODIFICAR           40007
#define ID_CLIENTES_ELIMINAR            40008
#define ID_BRUNCHYPROMO_AGREGAR         40009
#define ID_BRUNCHYPROMO_MOSTRAR         40010
#define ID_BRUNCHYPROMO_MODIFICAR       40011
#define ID_BRUNCHYPROMO_ELIMINAR        40012
#define ID_BRUNCHYPROMO_AGREGAR40013    40013
#define ID_BRUNCHYPROMO_MOSTRAR40014    40014
#define ID_BRUNCHYPROMO_MODIFICAR40015  40015
#define ID_BRUNCHYPROMO_ELIMINAR40016   40016
#define ID_BRUNCHYPROMO_VENTA           40017
#define ID_SUCURSALES_AGREGAR           40018
#define ID_SUCURSALES_MOSTRAR           40019
#define ID_SUCURSALES_MODIFICAR         40020
#define ID_SUCURSALES_ELIMINAR          40021
#define ID_SUCURSALES_ELIMINAR40022     40022
#define ID_CLIENTES_ELIMINAR12          40023
#define IDD_CLIENTES_ELIMINAR12         40024
#define ID_BRUNCHYPROMO_AGREGARR        40025
#define ID_CLIENTES_ELIMINARCLIENT      40026
#define ID_REPORTES_PUNTAJECLIENTES     40027
#define ID_REPORTES_BRUNCHYPROMOSCANJEADAS 40028
#define ID_REPORTES_VENTASTOTALESCLIENTES 40029
#define ID_BRUNCHYPROMO_CANJEARPROMOCION 40030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1263
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
